version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: blog_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - blognet
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: blog_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - blognet

    mysql:
        image: mysql:8
        container_name: blog_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blog
            MYSQL_USER: blog
            MYSQL_PASSWORD: blog
        ports:
            - "3307:3306"
        volumes:
            - blog_mysql_data:/var/lib/mysql
        networks:
            - blognet
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: blog_phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        depends_on:
            - mysql
        networks:
            - blognet


networks:
    blognet:

volumes:
    blog_mysql_data:
